
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-29 23:06:05.738361175 +0200 CEST
//code for table get_weburl_173826

package generteststruct



import (
	"restfest/db"
	"fmt"
	"time"
	"github.com/jackc/pgx"
			
)

type dummyGet_weburl_173826 time.Time

type Get_weburl_173826Params struct {
    P_id *int32
    P_start *int32
    P_end *int32
    P_len *int32
    P_lala *string
}

func (x *Get_weburl_173826Params) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.P_id,
				&x.P_start,
				&x.P_end,
				&x.P_len,
				&x.P_lala,
			}

}

func (x Get_weburl_173826) Reader(mapper map[string][]string) [][]string {
	return [][]string{
				}

}


func (x Get_weburl_173826Params) Reader(mapper map[string][]string) [][]string {
	return [][]string{
		mapper["p_id"],
		mapper["p_start"],
		mapper["p_end"],
		mapper["p_len"],
		mapper["p_lala"],
			}

}

type Get_weburl_173826 struct {
    Id int32  `json:"id"`
    Url *string  `json:"url"`
    Zusatz *int64  `json:"zusatz"`
    Created *time.Time  `json:"created"`
    W_cr_date *time.Time  `json:"w_cr_date"`
    W_upd_date *time.Time  `json:"w_upd_date"`
    W_upd_uid *string  `json:"w_upd_uid"`
    W_cr_uid *string  `json:"w_cr_uid"`
    Addtime *time.Time  `json:"addtime"`
    Addtime1 *time.Time  `json:"addtime1"`
    Flag bool  `json:"flag"`
    Test *float64  `json:"test"`
}

type ArGet_weburl_173826 []Get_weburl_173826



func (t Get_weburl_173826) Columns() []string {
	return []string{	 "id" ,	 "url" ,	 "zusatz" ,	 "created" ,	 "w_cr_date" ,	 "w_upd_date" ,	 "w_upd_uid" ,	 "w_cr_uid" ,	 "addtime" ,	 "addtime1" ,	 "flag" ,	 "test" ,
			}
}


func (x *Get_weburl_173826) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Id,
				&x.Url,
				&x.Zusatz,
				&x.Created,
				&x.W_cr_date,
				&x.W_upd_date,
				&x.W_upd_uid,
				&x.W_cr_uid,
				&x.Addtime,
				&x.Addtime1,
				&x.Flag,
				&x.Test,
			}

}

func (rt *Get_weburl_173826)ROWInsert() db.InterPgx {
	  return db.InterPgx{
		
  }
}


func (rt *Get_weburl_173826Params)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.P_id,
		&rt.P_start,
		&rt.P_end,
		&rt.P_len,
		&rt.P_lala,
}

}
				

func (dst *ArGet_weburl_173826) Scanner( rows *pgx.Rows) error {
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( Get_weburl_173826)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		*dst = append(*dst, *x)
	}
	return nil
}


type IterGet_weburl_173826 struct {
	db.BaseCopy
	Get_weburl_173826 Get_weburl_173826
}

type ArIterGet_weburl_173826 struct {
	IterGet_weburl_173826
	ArGet_weburl_173826 ArGet_weburl_173826
}



func (t *ArIterGet_weburl_173826) Next() bool {
	ok := t.IterGet_weburl_173826.Next()

 return ok
}

func (t *ArIterGet_weburl_173826) NewCopy(rows  *pgx.Rows) int {
 t.BaseCopy.NewCopy(rows,&t.Get_weburl_173826)
	for t.IterGet_weburl_173826.Next(){
		t.ArGet_weburl_173826 = append(t.ArGet_weburl_173826,t.Get_weburl_173826)
	}
 return len(t.ArGet_weburl_173826)
}

func (t *IterGet_weburl_173826) NewCopy(rows  *pgx.Rows)  {

 t.BaseCopy.NewCopy(rows,&t.Get_weburl_173826)
return
}


func (t *IterGet_weburl_173826) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) (int, error) {

	return t.BaseCopy.StartCopy(tab, con, tt, rows, &t.Get_weburl_173826)

}




			


func ( dst Get_weburl_173826Params)SQL(flag db.SQLOper)string{
  x :=   "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid,addtime,addtime1,flag,test"

  switch flag{
			

		case db.GenFunction:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
 "get_weburl" ,
 "$1,$2,$3,$4,$5"	,
		)


  }

	return ""

}




func ( dst Get_weburl_173826)SQL(flag db.SQLOper)string{
  x :=   "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid,addtime,addtime1,flag,test"

  switch flag{
			

		case db.GenFunction:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
 "get_weburl" ,
 "$1,$2,$3,$4,$5"	,
		)


  }

	return ""

}
