
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-29 23:06:05.503537505 +0200 CEST
//code for table pk_select

package generteststruct



import (
	"restfest/db"
	"fmt"
	"time"
	"github.com/jackc/pgx"
			
)

type dummyPk_select time.Time

type Pk_selectParams struct {
    Length int
    Offset int
}

func (x *Pk_selectParams) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Length,
				&x.Offset,
			}

}

func (x Pk_select) Reader(mapper map[string][]string) [][]string {
	return [][]string{
				}

}


func (x Pk_selectParams) Reader(mapper map[string][]string) [][]string {
	return [][]string{
		mapper["length"],
		mapper["offset"],
			}

}

type Pk_select struct {
    Table_name *string  `json:"table_name"`
    Column_name *string  `json:"column_name"`
}

type ArPk_select []Pk_select



func (t Pk_select) Columns() []string {
	return []string{	 "table_name" ,	 "column_name" ,
			}
}


func (x *Pk_select) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Table_name,
				&x.Column_name,
			}

}

func (rt *Pk_select)ROWInsert() db.InterPgx {
	  return db.InterPgx{
			&rt.Column_name,
    
  }
}


func (rt *Pk_selectParams)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.Length,
		&rt.Offset,
}

}
				
				type MapPk_select map[string]Pk_select
				type MapIterPk_select struct {
					IterPk_select
					MapPk_select  MapPk_select
				}

				func (t *MapIterPk_select) Next() bool {
					ok := t.IterPk_select.Next()

				 return ok
				}

				func (t *MapIterPk_select) NewCopy(rows  *pgx.Rows) int {
				 t.BaseCopy.NewCopy(rows,&t.Pk_select)
				 t.MapPk_select=make(MapPk_select)
					for t.IterPk_select.Next(){
						t.MapPk_select[*t.Pk_select.Table_name] = t.Pk_select
					}
				 return len(t.MapPk_select)
				}


	

func (dst *ArPk_select) Scanner( rows *pgx.Rows) error {
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( Pk_select)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		*dst = append(*dst, *x)
	}
	return nil
}


type IterPk_select struct {
	db.BaseCopy
	Pk_select Pk_select
}

type ArIterPk_select struct {
	IterPk_select
	ArPk_select ArPk_select
}



func (t *ArIterPk_select) Next() bool {
	ok := t.IterPk_select.Next()

 return ok
}

func (t *ArIterPk_select) NewCopy(rows  *pgx.Rows) int {
 t.BaseCopy.NewCopy(rows,&t.Pk_select)
	for t.IterPk_select.Next(){
		t.ArPk_select = append(t.ArPk_select,t.Pk_select)
	}
 return len(t.ArPk_select)
}

func (t *IterPk_select) NewCopy(rows  *pgx.Rows)  {

 t.BaseCopy.NewCopy(rows,&t.Pk_select)
return
}


func (t *IterPk_select) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) (int, error) {

	return t.BaseCopy.StartCopy(tab, con, tt, rows, &t.Pk_select)

}




			


func ( dst Pk_selectParams)SQL(flag db.SQLOper)string{
  x :=   "table_name,column_name"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "pk_select"	,
      "table_name" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "pk_select"	,
  		)


			
  }

	return ""

}




func ( dst Pk_select)SQL(flag db.SQLOper)string{
  x :=   "table_name,column_name"

  switch flag{
			


		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"pk_select"	,
			 "column_name"  ,
			 "$1" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"pk_select"	,
						"table_name",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"pk_select"	,
						"column_name=$1"  ,
						"table_name=$2",
					x)

			
  }

	return ""

}
