
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-29 23:06:05.6207699 +0200 CEST
//code for table t_master

package generteststruct



import (
	"restfest/db"
	"fmt"
	"time"
	"github.com/jackc/pgx"
			
)

type dummyT_master time.Time

type T_masterParams struct {
    Length int
    Offset int
}

func (x *T_masterParams) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Length,
				&x.Offset,
			}

}

func (x T_master) Reader(mapper map[string][]string) [][]string {
	return [][]string{
				}

}


func (x T_masterParams) Reader(mapper map[string][]string) [][]string {
	return [][]string{
		mapper["length"],
		mapper["offset"],
			}

}

type T_master struct {
    Id int32  `json:"id"`
    Lulu *string  `json:"lulu"`
    Lulu1 *string  `json:"lulu1"`
}

type ArT_master []T_master



func (t T_master) Columns() []string {
	return []string{	 "id" ,	 "lulu" ,	 "lulu1" ,
			}
}


func (x *T_master) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Id,
				&x.Lulu,
				&x.Lulu1,
			}

}

func (rt *T_master)ROWInsert() db.InterPgx {
	  return db.InterPgx{
			&rt.Lulu,	&rt.Lulu1,
    
  }
}


func (rt *T_masterParams)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.Length,
		&rt.Offset,
}

}
				
				type MapT_master map[int32]T_master
				type MapIterT_master struct {
					IterT_master
					MapT_master  MapT_master
				}

				func (t *MapIterT_master) Next() bool {
					ok := t.IterT_master.Next()

				 return ok
				}

				func (t *MapIterT_master) NewCopy(rows  *pgx.Rows) int {
				 t.BaseCopy.NewCopy(rows,&t.T_master)
				 t.MapT_master=make(MapT_master)
					for t.IterT_master.Next(){
						t.MapT_master[t.T_master.Id] = t.T_master
					}
				 return len(t.MapT_master)
				}


	

func (dst *ArT_master) Scanner( rows *pgx.Rows) error {
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( T_master)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		*dst = append(*dst, *x)
	}
	return nil
}


type IterT_master struct {
	db.BaseCopy
	T_master T_master
}

type ArIterT_master struct {
	IterT_master
	ArT_master ArT_master
}



func (t *ArIterT_master) Next() bool {
	ok := t.IterT_master.Next()

 return ok
}

func (t *ArIterT_master) NewCopy(rows  *pgx.Rows) int {
 t.BaseCopy.NewCopy(rows,&t.T_master)
	for t.IterT_master.Next(){
		t.ArT_master = append(t.ArT_master,t.T_master)
	}
 return len(t.ArT_master)
}

func (t *IterT_master) NewCopy(rows  *pgx.Rows)  {

 t.BaseCopy.NewCopy(rows,&t.T_master)
return
}


func (t *IterT_master) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) (int, error) {

	return t.BaseCopy.StartCopy(tab, con, tt, rows, &t.T_master)

}




			


func ( dst T_masterParams)SQL(flag db.SQLOper)string{
  x :=   "id,lulu,lulu1"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "t_master"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "t_master"	,
  		)


			
  }

	return ""

}




func ( dst T_master)SQL(flag db.SQLOper)string{
  x :=   "id,lulu,lulu1"

  switch flag{
			


		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"t_master"	,
			 "lulu,lulu1"  ,
			 "$1,$2" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"lulu=$1,lulu1=$2"  ,
						"id=$3",
					x)

			
  }

	return ""

}
