
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-20 21:11:00.972354194 +0200 CEST
//code for table get_weburl_173826

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyGet_weburl_173826 time.Time

type Get_weburl_173826Params struct {
    P_id *int32 `schema:"p_id"`
    P_start *int32 `schema:"p_start"`
    P_end *int32 `schema:"p_end"`
    P_len *int32 `schema:"p_len"`
    P_lala *string `schema:"p_lala"`
}


type Get_weburl_173826 struct {
    Id int32  `json:"id"`
    Url *string  `json:"url"`
    Zusatz *int64  `json:"zusatz"`
    Created *time.Time  `json:"created"`
    W_cr_date *time.Time  `json:"w_cr_date"`
    W_upd_date *time.Time  `json:"w_upd_date"`
    W_upd_uid *string  `json:"w_upd_uid"`
    W_cr_uid *string  `json:"w_cr_uid"`
    Addtime *time.Time  `json:"addtime"`
    Addtime1 *time.Time  `json:"addtime1"`
    Flag bool  `json:"flag"`
    Test *float64  `json:"test"`
}

type ArGet_weburl_173826 []Get_weburl_173826

			

func ScannerGet_weburl_173826I(struT *Get_weburl_173826)  db.InterPgx  {

	return []interface{}{
				&struT.Id,
				&struT.Url,
				&struT.Zusatz,
				&struT.Created,
				&struT.W_cr_date,
				&struT.W_upd_date,
				&struT.W_upd_uid,
				&struT.W_cr_uid,
				&struT.Addtime,
				&struT.Addtime1,
				&struT.Flag,
				&struT.Test,
			}

}


func SQLGet_weburl_173826(flag db.SQLOper)string{
  x :=   "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid,addtime,addtime1,flag,test"

  switch flag{
			

		case db.GenFunction:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
 "get_weburl" ,
 "$1,$2,$3,$4,$5"	,
		)


  }

	return ""

}


func EmptyGet_weburl_173826() interface{}{
    return new(Get_weburl_173826)
}


func EmptyParamGet_weburl_173826() interface{}{

 rt := new(Get_weburl_173826Params)

	

    return rt
}

func ScannerGet_weburl_173826()(  db.InterPgx , interface{}){
	struT := new(Get_weburl_173826)

return  ScannerGet_weburl_173826I(struT), struT

}


func ROWInsertGet_weburl_173826(inter interface{}) db.InterPgx {
					
  return []interface{}{
				
  }

}


func ROWQueryGet_weburl_173826(inter interface{}) db.InterPgx {
  rt := inter.( *Get_weburl_173826Params )

  return []interface{}{
		&rt.P_id,
		&rt.P_start,
		&rt.P_end,
		&rt.P_len,
		&rt.P_lala,
}

}
