
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-05-01 12:49:44.863236158 +0200 CEST
//code for table get_all_boo_173824

package generrester



import (
	"restfest/db"
	"fmt"
	"time"
	"io"
	"strings"
		"encoding/json"
	"github.com/jackc/pgx"
			
)

type dummyGet_all_boo_173824 time.Time

type Get_all_boo_173824Params struct {
    P_start *int32
    P_end *int32
    P_len *int32
    P_lala *string
}

type Get_all_boo_173824 struct {
    Id int32  `json:"id"`
    Url *string  `json:"url"`
    Zusatz *int64  `json:"zusatz"`
    Created *time.Time  `json:"created"`
    W_cr_date *time.Time  `json:"w_cr_date"`
    W_upd_date *time.Time  `json:"w_upd_date"`
    W_upd_uid *string  `json:"w_upd_uid"`
    W_cr_uid *string  `json:"w_cr_uid"`
    Addtime *time.Time  `json:"addtime"`
    Addtime1 *time.Time  `json:"addtime1"`
    Flag bool  `json:"flag"`
    Test *float64  `json:"test"`
}

type ArGet_all_boo_173824 []Get_all_boo_173824



var  Get_all_boo_173824SQL  =db.ColumnLists{
	 "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid,addtime,addtime1,flag,test",
	  "id,url,zusatz,created,w_cr_date,w_cr_uid,addtime,addtime1,flag,test"  ,
		 "$1,$2,$3,$4,current_timestamp,'webSrv',$5,$6,$7,$8" ,
	   "get_all_boo" ,
		 "get_all_boo=$9",
		"$1,$2,$3,$4"	 ,
						"id=$1,url=$2,zusatz=$3,created=$4,w_upd_date=current_timestamp,w_upd_uid='webSrv',addtime=$5,addtime1=$6,flag=$7,test=$8"  ,

}


func (x *Get_all_boo_173824Params) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.P_start,
				&x.P_end,
				&x.P_len,
				&x.P_lala,
			}

}

func (x Get_all_boo_173824) Reader(mapper map[string][]string) [][]string {
	return [][]string{
				}

}


func (x Get_all_boo_173824Params) Reader(mapper map[string][]string) [][]string {
	return [][]string{
		mapper["p_start"],
		mapper["p_end"],
		mapper["p_len"],
		mapper["p_lala"],
			}

}



func (t Get_all_boo_173824) Columns() []string {
	return strings.Split(Get_all_boo_173824SQL.All,",")
}


func (x *Get_all_boo_173824) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Id,
				&x.Url,
				&x.Zusatz,
				&x.Created,
				&x.W_cr_date,
				&x.W_upd_date,
				&x.W_upd_uid,
				&x.W_cr_uid,
				&x.Addtime,
				&x.Addtime1,
				&x.Flag,
				&x.Test,
			}

}

func (rt *Get_all_boo_173824)ROWInsert() db.InterPgx {
	  return db.InterPgx{
		
  }
}


func (rt *Get_all_boo_173824Params)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.P_start,
		&rt.P_end,
		&rt.P_len,
		&rt.P_lala,
}

}



func (t Get_all_boo_173824) Writer(w io.Writer,trenner string)  error {
		w.Write([]byte(trenner))

if err := json.NewEncoder(w).Encode(t); err != nil {
	return err
}
	return nil
}




func ( dst Get_all_boo_173824Params)SQL(flag db.SQLOper)string{


  switch flag{
			

		case db.GenFunction:
		return fmt.Sprintf(db.SQLPattern[flag],
	Get_all_boo_173824SQL.All,
Get_all_boo_173824SQL.PK,
 Get_all_boo_173824SQL.BindsVarInsert,
		)


  }

	return ""

}




func ( dst Get_all_boo_173824)SQL(flag db.SQLOper)string{


  switch flag{
			

		case db.GenFunction:
		return fmt.Sprintf(db.SQLPattern[flag],
		Get_all_boo_173824SQL.All,
Get_all_boo_173824SQL.PK,
Get_all_boo_173824SQL.BindsVarInsert,
		)


  }

	return ""

}



type IterGet_all_boo_173824 struct {
	db.BaseCopy
	Get_all_boo_173824 Get_all_boo_173824
}

type ArIterGet_all_boo_173824 struct {
	IterGet_all_boo_173824
	ArGet_all_boo_173824 ArGet_all_boo_173824
}


				



func (t *ArIterGet_all_boo_173824) NewCopy(rows  *pgx.Rows) int {
 t.BaseCopy.NewCopy(rows,&t.Get_all_boo_173824)
	for t.IterGet_all_boo_173824.Next(){
		t.ArGet_all_boo_173824 = append(t.ArGet_all_boo_173824,t.Get_all_boo_173824)
	}
 return len(t.ArGet_all_boo_173824)
}

func (t *IterGet_all_boo_173824) NewCopy(rows  *pgx.Rows)  {

 t.BaseCopy.NewCopy(rows,&t.Get_all_boo_173824)
return
}

func (t *IterGet_all_boo_173824) Value() db.PgxGener  {

 return &t.Get_all_boo_173824
}

func (t *IterGet_all_boo_173824) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) (int, error) {

	return t.BaseCopy.StartCopy(tab, con, tt, rows, &t.Get_all_boo_173824)

}




			
