
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-21 19:51:48.506575589 +0200 CEST
//code for table guges

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyGuges time.Time

type GugesParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Guges struct {
    Id int32  `json:"id"`
    A Weburl  `json:"a"`
}

type ArGuges []Guges

func (x *Guges) Scanner() db.InterPgx {
	return []interface{}{
				&x.Id,
				&x.A,
			}

}

func (rt *Guges)ROWInsert() db.InterPgx {
	  return []interface{}{
				
	&rt.A,

  }
}


func (rt *GugesParams)ROWInsert() db.InterPgx {

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}


			


func SQLGuges(flag db.SQLOper)string{
  x :=   "id,a"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "guges"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "guges"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"guges"	,
			 "a"  ,
			 "$1" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"guges"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"guges"	,
						"a=$1"  ,
						"id=$2",
					x)

			
  }

	return ""

}


func EmptyGuges() db.PgxGener{
    return new(Guges)
}

func EmptyInsGuges() db.PgxGenerIns{
    return new(Guges)
}

func EmptyParamGuges() db.PgxGenerIns{

 rt := new(GugesParams)

	
		rt.Length=100
	

    return rt
}
