
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-26 19:47:45.507525108 +0200 CEST
//code for table guges1

package generrester



import (
	"restfest/db"
	"fmt"
	"time"
	"io"
	"github.com/jackc/pgx"
			
)

type dummyGuges1 time.Time

type Guges1Params struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Guges1 struct {
    Id int32  `json:"id"`
    Agger ArWeburl  `json:"agger"`
    Texter *string  `json:"texter"`
    Zahler *int32  `json:"zahler"`
    Zahler2 *int32  `json:"zahler2"`
    Texter2 *string  `json:"texter2"`
}

type ArGuges1 []Guges1



func (t Guges1) Columns() []string {
	return []string{	 "id" ,	 "agger" ,	 "texter" ,	 "zahler" ,	 "zahler2" ,	 "texter2" ,
			}
}


func (x *Guges1) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Id,
				&x.Agger,
				&x.Texter,
				&x.Zahler,
				&x.Zahler2,
				&x.Texter2,
			}

}

func (rt *Guges1)ROWInsert() db.InterPgx {
	  return db.InterPgx{
			&rt.Agger,	&rt.Texter,	&rt.Zahler,	&rt.Zahler2,	&rt.Texter2,
    
  }
}


func (rt *Guges1Params)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.Length,
		&rt.Offset,
}

}
				
				type MapGuges1 map[int32]Guges1
func (dst *MapGuges1) Scanner( rows *pgx.Rows) error {

	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( Guges1)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		(*dst)[x.Id] = *x
	}

	return nil
}
	

func (dst *ArGuges1) Scanner( rows *pgx.Rows) error {
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( Guges1)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		*dst = append(*dst, *x)
	}
	return nil
}


type BaseCopyGuges1 struct {
	Errc      error
	Inter    db.InterPgx
	Rows     *pgx.Rows
	Guges1 Guges1
}

func (t *BaseCopyGuges1) Values() ([]interface{}, error) {
	return t.Inter, t.Errc
}


func (t *BaseCopyGuges1) ValuesString() (record []string,err error) {
record, err = t.Inter.ConvertItoS()
return
}


func (t BaseCopyGuges1) Err() error {
	if t.Errc != io.EOF {
		return t.Errc
	}
	return nil
}

func (t *BaseCopyGuges1) NewCopy(rows  *pgx.Rows)  {

	t.Inter = t.Guges1.Scanner()
t.Rows = rows
return
}


func (t *BaseCopyGuges1) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) error {

	t.Inter = t.Guges1.Scanner()
t.Rows = rows
	fmt.Println("vor copy", tab)
	copyCount, err := con.CopyFrom(
		[]string{tab},
		t.Guges1.Columns(),
		tt)

	fmt.Println("fertig", copyCount, err)
	if err != nil {
		return err
	}
	return nil
}

func (t *BaseCopyGuges1) Next() bool {
	var ok bool
	for {
		ok = t.Rows.Next()
		if !ok {
			break
		}
		t.Rows.Scan(t.Inter...)
		break
	}
	t.Errc = t.Rows.Err()
	if t.Errc != nil {
		return false
	}
	return ok

}



			


func SQLGuges1(flag db.SQLOper)string{
  x :=   "id,agger,texter,zahler,zahler2,texter2"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "guges1"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "guges1"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"guges1"	,
			 "agger,texter,zahler,zahler2,texter2"  ,
			 "$1,$2,$3,$4,$5" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"guges1"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"guges1"	,
						"agger=$1,texter=$2,zahler=$3,zahler2=$4,texter2=$5"  ,
						"id=$6",
					x)

			
  }

	return ""

}
