
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-29 22:56:40.001950064 +0200 CEST
//code for table logger

package generrester



import (
	"restfest/db"
	"fmt"
	"time"
	"github.com/jackc/pgx"
			
)

type dummyLogger time.Time

type LoggerParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}

func (x *LoggerParams) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Length,
				&x.Offset,
			}

}

func (x Logger) Reader(mapper map[string][]string) [][]string {
	return [][]string{
				}

}


func (x LoggerParams) Reader(mapper map[string][]string) [][]string {
	return [][]string{
		mapper["length"],
		mapper["offset"],
			}

}

type Logger struct {
    Seq int32  `json:"seq"`
    Id *int32  `json:"id"`
    Typ *string  `json:"typ"`
    Tablename *string  `json:"tablename"`
    Rower *map[string]interface{}  `json:"rower"`
}

type ArLogger []Logger



func (t Logger) Columns() []string {
	return []string{	 "seq" ,	 "id" ,	 "typ" ,	 "tablename" ,	 "rower" ,
			}
}


func (x *Logger) Scanner() db.InterPgx {
	return db.InterPgx{
				&x.Seq,
				&x.Id,
				&x.Typ,
				&x.Tablename,
				&x.Rower,
			}

}

func (rt *Logger)ROWInsert() db.InterPgx {
	  return db.InterPgx{
			&rt.Id,	&rt.Typ,	&rt.Tablename,	&rt.Rower,
    
  }
}


func (rt *LoggerParams)ROWInsert() db.InterPgx {
  return db.InterPgx{
		&rt.Length,
		&rt.Offset,
}

}
				
				type MapLogger map[int32]Logger
				type MapIterLogger struct {
					IterLogger
					MapLogger  MapLogger
				}

				func (t *MapIterLogger) Next() bool {
					ok := t.IterLogger.Next()

				 return ok
				}

				func (t *MapIterLogger) NewCopy(rows  *pgx.Rows) int {
				 t.BaseCopy.NewCopy(rows,&t.Logger)
					for t.IterLogger.Next(){
						t.MapLogger[t.Logger.Seq] = t.Logger
					}
				 return len(t.MapLogger)
				}


	

func (dst *ArLogger) Scanner( rows *pgx.Rows) error {
	for rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		x := new( Logger)
		if err := rows.Scan(x.Scanner()...); err != nil {
			return err
		}
		*dst = append(*dst, *x)
	}
	return nil
}


type IterLogger struct {
	db.BaseCopy
	Logger Logger
}

type ArIterLogger struct {
	IterLogger
	ArLogger ArLogger
}



func (t *ArIterLogger) Next() bool {
	ok := t.IterLogger.Next()

 return ok
}

func (t *ArIterLogger) NewCopy(rows  *pgx.Rows) int {
 t.BaseCopy.NewCopy(rows,&t.Logger)
	for t.IterLogger.Next(){
		t.ArLogger = append(t.ArLogger,t.Logger)
	}
 return len(t.ArLogger)
}

func (t *IterLogger) NewCopy(rows  *pgx.Rows)  {

 t.BaseCopy.NewCopy(rows,&t.Logger)
return
}


func (t *IterLogger) StartCopy(tab string, con *pgx.Conn, tt pgx.CopyFromSource,rows  *pgx.Rows) (int, error) {

	return t.BaseCopy.StartCopy(tab, con, tt, rows, &t.Logger)

}




			


func ( dst LoggerParams)SQL(flag db.SQLOper)string{
  x :=   "seq,id,typ,tablename,rower"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "logger"	,
      "seq" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "logger"	,
  		)


			
  }

	return ""

}




func ( dst Logger)SQL(flag db.SQLOper)string{
  x :=   "seq,id,typ,tablename,rower"

  switch flag{
			


		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"logger"	,
			 "id,typ,tablename,rower"  ,
			 "$1,$2,$3,$4" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"logger"	,
						"seq",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"logger"	,
						"id=$1,typ=$2,tablename=$3,rower=$4"  ,
						"seq=$5",
					x)

			
  }

	return ""

}
