
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-20 21:11:00.696072931 +0200 CEST
//code for table pk_select

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyPk_select time.Time

type Pk_selectParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Pk_select struct {
    Table_name *string  `json:"table_name"`
    Column_name *string  `json:"column_name"`
}

type ArPk_select []Pk_select

			

func ScannerPk_selectI(struT *Pk_select)  db.InterPgx  {

	return []interface{}{
				&struT.Table_name,
				&struT.Column_name,
			}

}


func SQLPk_select(flag db.SQLOper)string{
  x :=   "table_name,column_name"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "pk_select"	,
      "table_name" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "pk_select"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"pk_select"	,
			 "column_name"  ,
			 "$1" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"pk_select"	,
						"table_name",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"pk_select"	,
						"column_name=$1"  ,
						"table_name=$2",
					x)

			
  }

	return ""

}


func EmptyPk_select() interface{}{
    return new(Pk_select)
}


func EmptyParamPk_select() interface{}{

 rt := new(Pk_selectParams)

	
		rt.Length=100
	

    return rt
}

func ScannerPk_select()(  db.InterPgx , interface{}){
	struT := new(Pk_select)

return  ScannerPk_selectI(struT), struT

}


func ROWInsertPk_select(inter interface{}) db.InterPgx {
					
  rt := inter.( *Pk_select )
	
  return []interface{}{
				
	&rt.Column_name,

  }

}


func ROWQueryPk_select(inter interface{}) db.InterPgx {
  rt := inter.( *Pk_selectParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
