
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-21 19:51:48.767012096 +0200 CEST
//code for table t_master

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyT_master time.Time

type T_masterParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type T_master struct {
    Id int32  `json:"id"`
    Lulu *string  `json:"lulu"`
    Lulu1 *string  `json:"lulu1"`
}

type ArT_master []T_master

func (x *T_master) Scanner() db.InterPgx {
	return []interface{}{
				&x.Id,
				&x.Lulu,
				&x.Lulu1,
			}

}

func (rt *T_master)ROWInsert() db.InterPgx {
	  return []interface{}{
				
	&rt.Lulu,
	&rt.Lulu1,

  }
}


func (rt *T_masterParams)ROWInsert() db.InterPgx {

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}


			


func SQLT_master(flag db.SQLOper)string{
  x :=   "id,lulu,lulu1"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "t_master"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "t_master"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"t_master"	,
			 "lulu,lulu1"  ,
			 "$1,$2" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"lulu=$1,lulu1=$2"  ,
						"id=$3",
					x)

			
  }

	return ""

}


func EmptyT_master() db.PgxGener{
    return new(T_master)
}

func EmptyInsT_master() db.PgxGenerIns{
    return new(T_master)
}

func EmptyParamT_master() db.PgxGenerIns{

 rt := new(T_masterParams)

	
		rt.Length=100
	

    return rt
}
