
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-20 21:11:00.720005819 +0200 CEST
//code for table tedas

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyTedas time.Time

type TedasParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Tedas struct {
    Id int32  `json:"id"`
    Agg []int32  `json:"agg"`
}

type ArTedas []Tedas

			

func ScannerTedasI(struT *Tedas)  db.InterPgx  {

	return []interface{}{
				&struT.Id,
				&struT.Agg,
			}

}


func SQLTedas(flag db.SQLOper)string{
  x :=   "id,agg"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "tedas"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "tedas"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"tedas"	,
			 "agg"  ,
			 "$1" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"tedas"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"tedas"	,
						"agg=$1"  ,
						"id=$2",
					x)

			
  }

	return ""

}


func EmptyTedas() interface{}{
    return new(Tedas)
}


func EmptyParamTedas() interface{}{

 rt := new(TedasParams)

	
		rt.Length=100
	

    return rt
}

func ScannerTedas()(  db.InterPgx , interface{}){
	struT := new(Tedas)

return  ScannerTedasI(struT), struT

}


func ROWInsertTedas(inter interface{}) db.InterPgx {
					
  rt := inter.( *Tedas )
	
  return []interface{}{
				
	&rt.Agg,

  }

}


func ROWQueryTedas(inter interface{}) db.InterPgx {
  rt := inter.( *TedasParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
