
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-20 21:11:00.803962985 +0200 CEST
//code for table tester

package generrester



import (
	"restfest/db"
	"fmt"
	"time"

			
)

type dummyTester time.Time

type TesterParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Tester struct {
    Name *string  `json:"name"`
    Vorname *string  `json:"vorname"`
    Id int64  `json:"id"`
    Code *string  `json:"code"`
    Lala *string  `json:"lala"`
}

type ArTester []Tester

			

func ScannerTesterI(struT *Tester)  db.InterPgx  {

	return []interface{}{
				&struT.Name,
				&struT.Vorname,
				&struT.Id,
				&struT.Code,
				&struT.Lala,
			}

}


func SQLTester(flag db.SQLOper)string{
  x :=   "name,vorname,id,code,lala"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "tester"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "tester"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"tester"	,
			 "name,vorname,code,lala"  ,
			 "$1,$2,$3,$4" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"tester"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"tester"	,
						"name=$1,vorname=$2,code=$3,lala=$4"  ,
						"id=$5",
					x)

			
  }

	return ""

}


func EmptyTester() interface{}{
    return new(Tester)
}


func EmptyParamTester() interface{}{

 rt := new(TesterParams)

	
		rt.Length=100
	

    return rt
}

func ScannerTester()(  db.InterPgx , interface{}){
	struT := new(Tester)

return  ScannerTesterI(struT), struT

}


func ROWInsertTester(inter interface{}) db.InterPgx {
					
  rt := inter.( *Tester )
	
  return []interface{}{
				
	&rt.Name,
	&rt.Vorname,
	&rt.Code,
	&rt.Lala,

  }

}


func ROWQueryTester(inter interface{}) db.InterPgx {
  rt := inter.( *TesterParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
