// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-21 19:51:48.936007081 +0200 CEST

package main


import (
"restfest/generrester"
"restfest/db"

)


func init(){
	db.FunMap=map[string]db.TFunMap{
	
	"guges":{		generrester.SQLGuges,
		generrester.EmptyGuges,
				generrester.EmptyInsGuges,
		generrester.EmptyParamGuges,
		1, },
	
	"guges1":{		generrester.SQLGuges1,
		generrester.EmptyGuges1,
				generrester.EmptyInsGuges1,
		generrester.EmptyParamGuges1,
		1, },
	
	"get_guges1_174200":{		generrester.SQLGet_guges1_174200,
		generrester.EmptyGet_guges1_174200,
				generrester.EmptyInsGet_guges1_174200,
		generrester.EmptyParamGet_guges1_174200,
		3, },
	
	"lala":{		generrester.SQLLala,
		generrester.EmptyLala,
				generrester.EmptyInsLala,
		generrester.EmptyParamLala,
		2, },
	
	"lala1":{		generrester.SQLLala1,
		generrester.EmptyLala1,
				generrester.EmptyInsLala1,
		generrester.EmptyParamLala1,
		2, },
	
	"logger":{		generrester.SQLLogger,
		generrester.EmptyLogger,
				generrester.EmptyInsLogger,
		generrester.EmptyParamLogger,
		1, },
	
	"pk_select":{		generrester.SQLPk_select,
		generrester.EmptyPk_select,
				generrester.EmptyInsPk_select,
		generrester.EmptyParamPk_select,
		2, },
	
	"tedas":{		generrester.SQLTedas,
		generrester.EmptyTedas,
				generrester.EmptyInsTedas,
		generrester.EmptyParamTedas,
		1, },
	
	"testa":{		generrester.SQLTesta,
		generrester.EmptyTesta,
				generrester.EmptyInsTesta,
		generrester.EmptyParamTesta,
		1, },
	
	"testa1":{		generrester.SQLTesta1,
		generrester.EmptyTesta1,
				generrester.EmptyInsTesta1,
		generrester.EmptyParamTesta1,
		2, },
	
	"tester":{		generrester.SQLTester,
		generrester.EmptyTester,
				generrester.EmptyInsTester,
		generrester.EmptyParamTester,
		1, },
	
	"t_master":{		generrester.SQLT_master,
		generrester.EmptyT_master,
				generrester.EmptyInsT_master,
		generrester.EmptyParamT_master,
		1, },
	
	"t_random":{		generrester.SQLT_random,
		generrester.EmptyT_random,
				generrester.EmptyInsT_random,
		generrester.EmptyParamT_random,
		1, },
	
	"vtester":{		generrester.SQLVtester,
		generrester.EmptyVtester,
				generrester.EmptyInsVtester,
		generrester.EmptyParamVtester,
		2, },
	
	"vweburl":{		generrester.SQLVweburl,
		generrester.EmptyVweburl,
				generrester.EmptyInsVweburl,
		generrester.EmptyParamVweburl,
		2, },
	
	"get_weburl_173825":{		generrester.SQLGet_weburl_173825,
		generrester.EmptyGet_weburl_173825,
				generrester.EmptyInsGet_weburl_173825,
		generrester.EmptyParamGet_weburl_173825,
		3, },
	
	"weburl":{		generrester.SQLWeburl,
		generrester.EmptyWeburl,
				generrester.EmptyInsWeburl,
		generrester.EmptyParamWeburl,
		4, },
	
	"get_weburl_173826":{		generrester.SQLGet_weburl_173826,
		generrester.EmptyGet_weburl_173826,
				generrester.EmptyInsGet_weburl_173826,
		generrester.EmptyParamGet_weburl_173826,
		3, },
	
	"get_all_boo_173824":{		generrester.SQLGet_all_boo_173824,
		generrester.EmptyGet_all_boo_173824,
				generrester.EmptyInsGet_all_boo_173824,
		generrester.EmptyParamGet_all_boo_173824,
		3, },
}

}
