// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-20 20:20:37.545819303 +0200 CEST

package main


import (
"restfest/generrester"
"restfest/db"
)


func init(){
	db.FunMap=map[string]db.TFunMap{
	
	"guges":{
			generrester.SQLGuges,
	generrester.ROWInsertGuges,
		generrester.ROWQueryGuges,
		generrester.EmptyGuges,
		generrester.EmptyParamGuges,
		generrester.ScannerGuges,
		1, },
	
	"guges1":{
			generrester.SQLGuges1,
	generrester.ROWInsertGuges1,
		generrester.ROWQueryGuges1,
		generrester.EmptyGuges1,
		generrester.EmptyParamGuges1,
		generrester.ScannerGuges1,
		1, },
	
	"get_guges1_174200":{
			generrester.SQLGet_guges1_174200,
	generrester.ROWInsertGet_guges1_174200,
		generrester.ROWQueryGet_guges1_174200,
		generrester.EmptyGet_guges1_174200,
		generrester.EmptyParamGet_guges1_174200,
		generrester.ScannerGet_guges1_174200,
		3, },
	
	"lala":{
			generrester.SQLLala,
	generrester.ROWInsertLala,
		generrester.ROWQueryLala,
		generrester.EmptyLala,
		generrester.EmptyParamLala,
		generrester.ScannerLala,
		2, },
	
	"lala1":{
			generrester.SQLLala1,
	generrester.ROWInsertLala1,
		generrester.ROWQueryLala1,
		generrester.EmptyLala1,
		generrester.EmptyParamLala1,
		generrester.ScannerLala1,
		2, },
	
	"logger":{
			generrester.SQLLogger,
	generrester.ROWInsertLogger,
		generrester.ROWQueryLogger,
		generrester.EmptyLogger,
		generrester.EmptyParamLogger,
		generrester.ScannerLogger,
		1, },
	
	"pk_select":{
			generrester.SQLPk_select,
	generrester.ROWInsertPk_select,
		generrester.ROWQueryPk_select,
		generrester.EmptyPk_select,
		generrester.EmptyParamPk_select,
		generrester.ScannerPk_select,
		2, },
	
	"tedas":{
			generrester.SQLTedas,
	generrester.ROWInsertTedas,
		generrester.ROWQueryTedas,
		generrester.EmptyTedas,
		generrester.EmptyParamTedas,
		generrester.ScannerTedas,
		1, },
	
	"testa1":{
			generrester.SQLTesta1,
	generrester.ROWInsertTesta1,
		generrester.ROWQueryTesta1,
		generrester.EmptyTesta1,
		generrester.EmptyParamTesta1,
		generrester.ScannerTesta1,
		2, },
	
	"tester":{
			generrester.SQLTester,
	generrester.ROWInsertTester,
		generrester.ROWQueryTester,
		generrester.EmptyTester,
		generrester.EmptyParamTester,
		generrester.ScannerTester,
		1, },
	
	"t_master":{
			generrester.SQLT_master,
	generrester.ROWInsertT_master,
		generrester.ROWQueryT_master,
		generrester.EmptyT_master,
		generrester.EmptyParamT_master,
		generrester.ScannerT_master,
		1, },
	
	"t_random":{
			generrester.SQLT_random,
	generrester.ROWInsertT_random,
		generrester.ROWQueryT_random,
		generrester.EmptyT_random,
		generrester.EmptyParamT_random,
		generrester.ScannerT_random,
		1, },
	
	"vtester":{
			generrester.SQLVtester,
	generrester.ROWInsertVtester,
		generrester.ROWQueryVtester,
		generrester.EmptyVtester,
		generrester.EmptyParamVtester,
		generrester.ScannerVtester,
		2, },
	
	"vweburl":{
			generrester.SQLVweburl,
	generrester.ROWInsertVweburl,
		generrester.ROWQueryVweburl,
		generrester.EmptyVweburl,
		generrester.EmptyParamVweburl,
		generrester.ScannerVweburl,
		2, },
	
	"get_weburl_173825":{
			generrester.SQLGet_weburl_173825,
	generrester.ROWInsertGet_weburl_173825,
		generrester.ROWQueryGet_weburl_173825,
		generrester.EmptyGet_weburl_173825,
		generrester.EmptyParamGet_weburl_173825,
		generrester.ScannerGet_weburl_173825,
		3, },
	
	"weburl":{
			generrester.SQLWeburl,
	generrester.ROWInsertWeburl,
		generrester.ROWQueryWeburl,
		generrester.EmptyWeburl,
		generrester.EmptyParamWeburl,
		generrester.ScannerWeburl,
		4, },
	
	"get_weburl_173826":{
			generrester.SQLGet_weburl_173826,
	generrester.ROWInsertGet_weburl_173826,
		generrester.ROWQueryGet_weburl_173826,
		generrester.EmptyGet_weburl_173826,
		generrester.EmptyParamGet_weburl_173826,
		generrester.ScannerGet_weburl_173826,
		3, },
	
	"get_all_boo_173824":{
			generrester.SQLGet_all_boo_173824,
	generrester.ROWInsertGet_all_boo_173824,
		generrester.ROWQueryGet_all_boo_173824,
		generrester.EmptyGet_all_boo_173824,
		generrester.EmptyParamGet_all_boo_173824,
		generrester.ScannerGet_all_boo_173824,
		3, },
}

}
