// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-21 19:51:48.942496543 +0200 CEST

package main


import (
"restfest/generrester"
"restfest/db"
"fmt"
)


func init(){
	db.ConnectorFunMap=map[string]db.MapperFun2{"lala":generrester.ConnectorLala ,"weburl":generrester.ConnectorWeburl ,
}


db.InitDB()
	fmt.Printf("geladene Tabellen: %d\n", len(db.FunMap))
}
