// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-05-03 23:32:54.419156952 +0200 CEST

package main


import (
"restfest/generrester"
"restfest/db"

)


func init(){
	db.FunMap=map[string]db.TFunMap{
	
	"csvtest":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Csvtest)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Csvtest)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.CsvtestParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterCsvtest )
		},
		Flag:		1, },
	
	"guges":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Guges)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Guges)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.GugesParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGuges )
		},
		Flag:		1, },
	
	"guges1":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Guges1)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Guges1)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Guges1Params)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGuges1 )
		},
		Flag:		1, },
	
	"get_guges1":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Get_guges1)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Get_guges1)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Get_guges1Params)
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGet_guges1 )
		},
		Flag:		3, },
	
	"lala":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Lala)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Lala)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.LalaParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterLala )
		},
		Flag:		2, },
	
	"lala1":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Lala1)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Lala1)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Lala1Params)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterLala1 )
		},
		Flag:		2, },
	
	"logger":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Logger)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Logger)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.LoggerParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterLogger )
		},
		Flag:		1, },
	
	"los":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Los)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Los)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.LosParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterLos )
		},
		Flag:		1, },
	
	"pk_select":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Pk_select)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Pk_select)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Pk_selectParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterPk_select )
		},
		Flag:		2, },
	
	"tedas":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Tedas)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Tedas)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.TedasParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterTedas )
		},
		Flag:		1, },
	
	"testa":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Testa)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Testa)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.TestaParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterTesta )
		},
		Flag:		1, },
	
	"testa1":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Testa1)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Testa1)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Testa1Params)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterTesta1 )
		},
		Flag:		2, },
	
	"tester":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Tester)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Tester)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.TesterParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterTester )
		},
		Flag:		1, },
	
	"t_master":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.T_master)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.T_master)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.T_masterParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterT_master )
		},
		Flag:		1, },
	
	"t_random":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.T_random)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.T_random)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.T_randomParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterT_random )
		},
		Flag:		1, },
	
	"vtester":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Vtester)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Vtester)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.VtesterParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterVtester )
		},
		Flag:		2, },
	
	"vweburl":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Vweburl)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Vweburl)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.VweburlParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterVweburl )
		},
		Flag:		2, },
	
	"get_weburl_173825":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Get_weburl_173825)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Get_weburl_173825)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Get_weburl_173825Params)
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGet_weburl_173825 )
		},
		Flag:		3, },
	
	"weburl":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Weburl)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Weburl)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.WeburlParams)
			
				rt.Length=100
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterWeburl )
		},
		Flag:		4, },
	
	"get_all_boo":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Get_all_boo)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Get_all_boo)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Get_all_booParams)
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGet_all_boo )
		},
		Flag:		3, },
	
	"get_weburl":{
		EmptyFun:		func () db.PgxGener{
		    return new(generrester.Get_weburl)
		},
		EmptyInsFun:  func () db.PgxGenerIns{
		    return new(generrester.Get_weburl)
		},
				ParamFun: func () db.PgxGenerIns{
		 rt := new(generrester.Get_weburlParams)
			
		    return rt
		},
	 Iterator:	func () db.Iterator {
				return new( generrester.IterGet_weburl )
		},
		Flag:		3, },
}

}
