// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-05-01 21:19:06.500809932 +0200 CEST

package main


import (
"restfest/generrestspec"
"restfest/db"
"github.com/jackc/pgx"
"github.com/jackc/pgx/pgtype"
"fmt"
)


func init(){
	db.ConnectorFunMap=map[string]db.MapperFun2{
	  	 
	 "lala": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generrestspec.ArLala{},
	 		Name:  "generrestspec.ArLala",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generrestspec.Lala{},
	 		Name:  "generrestspec.Lala",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
	  	 
	 "weburl": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generrestspec.ArWeburl{},
	 		Name:  "generrestspec.ArWeburl",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generrestspec.Weburl{},
	 		Name:  "generrestspec.Weburl",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
}


db.InitDB()
	fmt.Printf("geladene Tabellen: %d\n", len(db.FunMap))
}
