// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-24 23:12:09.296707401 +0200 CEST

package main


import (
"restfest/generteststruct"
"restfest/db"
"github.com/jackc/pgx"
"github.com/jackc/pgx/pgtype"
"fmt"
)


func init(){
	db.ConnectorFunMap=map[string]db.MapperFun2{
	  	 
	 "lala": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generteststruct.ArLala{},
	 		Name:  "generteststruct.ArLala",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generteststruct.Lala{},
	 		Name:  "generteststruct.Lala",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
	  	 
	 "weburl": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generteststruct.ArWeburl{},
	 		Name:  "generteststruct.ArWeburl",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &generteststruct.Weburl{},
	 		Name:  "generteststruct.Weburl",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
}


db.InitDB()
	fmt.Printf("geladene Tabellen: %d\n", len(db.FunMap))
}
