// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-05-07 21:36:03.523701445 +0200 CEST

package main

import (
gener "restfest/teststruct/gener"
"restfest/db"
"github.com/jackc/pgx"
"github.com/jackc/pgx/pgtype"
"fmt"
)


func init(){
	db.ConnectorFunMap=map[string]db.MapperFun2{
	  	 
	 "lala": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &gener.ArLala{},
	 		Name:  "gener.ArLala",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &gener.Lala{},
	 		Name:  "gener.Lala",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
	  	 
	 "weburl": func (con *pgx.Conn, oida pgtype.Oid,oid pgtype.Oid) error {
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &gener.ArWeburl{},
	 		Name:  "gener.ArWeburl",
	 		Oid:  oida,
	 	})
	 	con.ConnInfo.RegisterDataType(pgtype.DataType{
	 		Value: &gener.Weburl{},
	 		Name:  "gener.Weburl",
	 		Oid:  oid,
	 	})
	 	return nil
	 } ,
	 
}


db.InitDB()
	fmt.Printf("geladene Tabellen: %d\n", len(db.FunMap))
}
