// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-02 18:15:13.500950974 +0200 CEST

package gener

var SQLFunMap = map[string]func(string, SQLOper) []interface{}{
	"webgaga":   SQLWebgaga,
	"t_random":  SQLT_random,
	"t_master":  SQLT_master,
	"tester":    SQLTester,
	"weburl":    SQLWeburl,
	"latest":    SQLLatest,
	"testa1":    SQLTesta1,
	"pk_select": SQLPk_select,
	"vtester":   SQLVtester,
	"vweburl":   SQLVweburl,
}

var ROWInsertFunMap = map[string]mapperFun1{
	"webgaga":   ROWInsertWebgaga,
	"t_random":  ROWInsertT_random,
	"t_master":  ROWInsertT_master,
	"tester":    ROWInsertTester,
	"weburl":    ROWInsertWeburl,
	"latest":    ROWInsertLatest,
	"testa1":    ROWInsertTesta1,
	"pk_select": ROWInsertPk_select,
	"vtester":   ROWInsertVtester,
	"vweburl":   ROWInsertVweburl,
}

var EmptyFunMap = map[string]func() []interface{}{
	"webgaga":   EmptyWebgaga,
	"t_random":  EmptyT_random,
	"t_master":  EmptyT_master,
	"tester":    EmptyTester,
	"weburl":    EmptyWeburl,
	"latest":    EmptyLatest,
	"testa1":    EmptyTesta1,
	"pk_select": EmptyPk_select,
	"vtester":   EmptyVtester,
	"vweburl":   EmptyVweburl,
}
var ROWSFunMap = map[string]mapperFun{
	"webgaga":   ROWSWebgaga,
	"t_random":  ROWST_random,
	"t_master":  ROWST_master,
	"tester":    ROWSTester,
	"weburl":    ROWSWeburl,
	"latest":    ROWSLatest,
	"testa1":    ROWSTesta1,
	"pk_select": ROWSPk_select,
	"vtester":   ROWSVtester,
	"vweburl":   ROWSVweburl,
}
