// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-03 21:55:29.076133879 +0200 CEST

package gener


import (
	"restfest/db"
)


var SQLFunMap =  map[string]func (string,db.SQLOper)[]interface{} {
"t_random": SQLT_random,
"t_master": SQLT_master,
"tester": SQLTester,
"weburl": SQLWeburl,
"testa1": SQLTesta1,
"pk_select": SQLPk_select,
"vtester": SQLVtester,
"vweburl": SQLVweburl,
}



var ROWInsertFunMap =  map[string]db.MapperFun1{
"t_random": ROWInsertT_random,
"t_master": ROWInsertT_master,
"tester": ROWInsertTester,
"weburl": ROWInsertWeburl,
"testa1": ROWInsertTesta1,
"pk_select": ROWInsertPk_select,
"vtester": ROWInsertVtester,
"vweburl": ROWInsertVweburl,
}

var EmptyFunMap =  map[string]func ()interface{}{
"t_random": EmptyT_random,
"t_master": EmptyT_master,
"tester": EmptyTester,
"weburl": EmptyWeburl,
"testa1": EmptyTesta1,
"pk_select": EmptyPk_select,
"vtester": EmptyVtester,
"vweburl": EmptyVweburl,
}

var ScannerFunMap = map[string]func ()( []interface{}, interface{}){
"t_random":ScannerT_random,
"t_master":ScannerT_master,
"tester":ScannerTester,
"weburl":ScannerWeburl,
"testa1":ScannerTesta1,
"pk_select":ScannerPk_select,
"vtester":ScannerVtester,
"vweburl":ScannerVweburl,
}
