// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-02 12:22:33.032356272 +0200 CEST

package gener


var SQLFunMap =  map[string]func ()([]string,string) {
"webgaga": SQLWebgaga,
"t_random": SQLT_random,
"t_master": SQLT_master,
"tester": SQLTester,
"weburl": SQLWeburl,
"latest": SQLLatest,
"testa1": SQLTesta1,
"pk_select": SQLPk_select,
"vtester": SQLVtester,
"vweburl": SQLVweburl,
}

var SQLInsertFunMap =  map[string]func ()([]string,[]string,[]string) {
"webgaga": SQLInsertWebgaga,
"t_random": SQLInsertT_random,
"t_master": SQLInsertT_master,
"tester": SQLInsertTester,
"weburl": SQLInsertWeburl,
"latest": SQLInsertLatest,
"testa1": SQLInsertTesta1,
"pk_select": SQLInsertPk_select,
"vtester": SQLInsertVtester,
"vweburl": SQLInsertVweburl,
}

var SQLUpdateFunMap =  map[string]func ()([]string, string,[]string){
"webgaga": SQLUpdateWebgaga,
"t_random": SQLUpdateT_random,
"t_master": SQLUpdateT_master,
"tester": SQLUpdateTester,
"weburl": SQLUpdateWeburl,
"latest": SQLUpdateLatest,
"testa1": SQLUpdateTesta1,
"pk_select": SQLUpdatePk_select,
"vtester": SQLUpdateVtester,
"vweburl": SQLUpdateVweburl,
}

var ROWUpdateFunMap =  map[string]mapperFun2{
"webgaga": ROWUpdateWebgaga,
"t_random": ROWUpdateT_random,
"t_master": ROWUpdateT_master,
"tester": ROWUpdateTester,
"weburl": ROWUpdateWeburl,
"latest": ROWUpdateLatest,
"testa1": ROWUpdateTesta1,
"pk_select": ROWUpdatePk_select,
"vtester": ROWUpdateVtester,
"vweburl": ROWUpdateVweburl,
}
var ROWInsertFunMap =  map[string]mapperFun1{
"webgaga": ROWInsertWebgaga,
"t_random": ROWInsertT_random,
"t_master": ROWInsertT_master,
"tester": ROWInsertTester,
"weburl": ROWInsertWeburl,
"latest": ROWInsertLatest,
"testa1": ROWInsertTesta1,
"pk_select": ROWInsertPk_select,
"vtester": ROWInsertVtester,
"vweburl": ROWInsertVweburl,
}

var EmptyFunMap =  map[string]func ()[]interface{}{
"webgaga": EmptyWebgaga,
"t_random": EmptyT_random,
"t_master": EmptyT_master,
"tester": EmptyTester,
"weburl": EmptyWeburl,
"latest": EmptyLatest,
"testa1": EmptyTesta1,
"pk_select": EmptyPk_select,
"vtester": EmptyVtester,
"vweburl": EmptyVweburl,
}
var ROWSFunMap =  map[string]mapperFun{
"webgaga": ROWSWebgaga,
"t_random": ROWST_random,
"t_master": ROWST_master,
"tester": ROWSTester,
"weburl": ROWSWeburl,
"latest": ROWSLatest,
"testa1": ROWSTesta1,
"pk_select": ROWSPk_select,
"vtester": ROWSVtester,
"vweburl": ROWSVweburl,
}
