
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-14 12:51:49.866462577 +0200 CEST
//code for table t_master

package gener



import (
	"restfest/db"
	"fmt"
	"time"
)

var dummyT_master time.Time

type T_masterParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type T_master struct {
    Id int32  `json:"id"`
    Lulu *string  `json:"lulu"`
    Lulu1 *string  `json:"lulu1"`
}



func SQLT_master(flag db.SQLOper)string{
  x :=   "id,lulu,lulu1"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "t_master"	,
      "id" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "t_master"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"t_master"	,
			 "lulu,lulu1"  ,
			 "$1,$2" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"t_master"	,
						"lulu=$1,lulu1=$2"  ,
						"id=$3",
					x)

			
  }

	return ""

}


func EmptyT_master() interface{}{
    return new(T_master)
}


func EmptyParamT_master() interface{}{

 rt := new(T_masterParams)

	
		rt.Length=100
	

    return rt
}

func ScannerT_master()( []interface{}, interface{}){
	struT := new(T_master)

return  []interface{}{
				&struT.Id,
				&struT.Lulu,
				&struT.Lulu1,
			}, struT

}


func ScannerTT_master()( []interface{},*T_master){
	struT := new(T_master)

return  []interface{}{
				&struT.Id,
				&struT.Lulu,
				&struT.Lulu1,
			}, struT

}


func ROWInsertT_master(inter interface{})[]interface{}{
					
  rt := inter.( *T_master )
	
  return []interface{}{
				
	&rt.Lulu,
	&rt.Lulu1,

  }

}


func ROWQueryT_master(inter interface{})[]interface{}{
  rt := inter.( *T_masterParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
