
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-11 21:36:51.460302405 +0200 CEST
//code for table tester

package gener



import (
	"restfest/db"
	"fmt"
	"time"
)

var dummyTester time.Time

type TesterParams struct {
    Length *int64 `schema:"length"`
    Offset *int64 `schema:"offset"`
}


type Tester struct {
    Name db.JSONString  `json:"name"`
    Vorname db.JSONString  `json:"vorname"`
    Id *int64  `json:"id"`
    Code db.JSONString  `json:"code"`
    Lala *int64  `json:"lala"`
}



func SQLTester(flag db.SQLOper)string{
  x :=   "name,vorname,id,code,lala"

  switch flag{
			
    case db.GenSelectID:
    return fmt.Sprintf(db.SQLPattern[db.GenSelectID],
    x,
	     "tester"	,
      "id" ,
    )

		case db.GenSelectAll:
		return fmt.Sprintf(db.SQLPattern[db.GenSelectAll],
		x,
   "tester"	,
  "id",
		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[db.GenInsert],
			"tester"	,
			 "name,vorname,code,lala"  ,
			 "$1,$2,$3,$4" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[db.GenDelete]  ,
					"tester"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[db.GenUpdate]  ,
					"tester"	,
						"name=$1,vorname=$2,code=$3,lala=$4"  ,
						"id=$5",
					x)

			
  }

	return ""

}


func EmptyTester() interface{}{
    return new(Tester)
}


func EmptyParamTester() interface{}{

 rt := new(TesterParams)

	
		tt := new(int64)
		*tt = 100
		rt.Length=tt
				tt = new(int64)
 	*tt = 0
 	rt.Offset=tt

	

    return rt
}

func ScannerTester()( []interface{}, interface{}){
	struT := new(Tester)

return  []interface{}{
				&struT.Name,
				&struT.Vorname,
				&struT.Id,
				&struT.Code,
				&struT.Lala,
			}, struT

}


func ScannerTTester()( []interface{},*Tester){
	struT := new(Tester)

return  []interface{}{
				&struT.Name,
				&struT.Vorname,
				&struT.Id,
				&struT.Code,
				&struT.Lala,
			}, struT

}


func ROWInsertTester(inter interface{})[]interface{}{
					
  rt := inter.( *Tester )
	
  return []interface{}{
				
	&rt.Name,
	&rt.Vorname,
	&rt.Code,
	&rt.Lala,

  }

}


func ROWQueryTester(inter interface{})[]interface{}{
  rt := inter.( *TesterParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
