
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-14 12:51:49.949673198 +0200 CEST
//code for table vtester

package gener



import (
	"restfest/db"
	"fmt"
	"time"
)

var dummyVtester time.Time

type VtesterParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Vtester struct {
    Name *string  `json:"name"`
    Vorname *string  `json:"vorname"`
    Id *int64  `json:"id"`
    Code *string  `json:"code"`
    Lala *string  `json:"lala"`
}



func SQLVtester(flag db.SQLOper)string{
  x :=   "name,vorname,id,code,lala"

  switch flag{
			
    case db.GenSelectID,  db.GenSelectAll:
    return fmt.Sprintf(db.SQLPattern[flag],
    x,
	     "vtester"	,
      "name" ,
    )

		case db.GenSelectAll1:
		return fmt.Sprintf(db.SQLPattern[flag],
		x,
   "vtester"	,
  		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[flag],
			"vtester"	,
			 "vorname,id,code,lala"  ,
			 "$1,$2,$3,$4" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"vtester"	,
						"name",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[flag]  ,
					"vtester"	,
						"vorname=$1,id=$2,code=$3,lala=$4"  ,
						"name=$5",
					x)

			
  }

	return ""

}


func EmptyVtester() interface{}{
    return new(Vtester)
}


func EmptyParamVtester() interface{}{

 rt := new(VtesterParams)

	
		rt.Length=100
	

    return rt
}

func ScannerVtester()( []interface{}, interface{}){
	struT := new(Vtester)

return  []interface{}{
				&struT.Name,
				&struT.Vorname,
				&struT.Id,
				&struT.Code,
				&struT.Lala,
			}, struT

}


func ScannerTVtester()( []interface{},*Vtester){
	struT := new(Vtester)

return  []interface{}{
				&struT.Name,
				&struT.Vorname,
				&struT.Id,
				&struT.Code,
				&struT.Lala,
			}, struT

}


func ROWInsertVtester(inter interface{})[]interface{}{
					
  rt := inter.( *Vtester )
	
  return []interface{}{
				
	&rt.Vorname,
	&rt.Id,
	&rt.Code,
	&rt.Lala,

  }

}


func ROWQueryVtester(inter interface{})[]interface{}{
  rt := inter.( *VtesterParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
