
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-03 23:38:38.404420348 +0200 CEST
//code for table vweburl

package gener


import (
	"restfest/db"
)

type Vweburl struct {
    Id db.JSONNullInt64  `json:"id"`
    Url db.JSONNullString  `json:"url"`
    Zusatz db.JSONNullInt64  `json:"zusatz"`
    Created db.JSONNullString  `json:"created"`
    W_cr_date db.JSONNullString  `json:"w_cr_date"`
    W_upd_date db.JSONNullString  `json:"w_upd_date"`
    W_upd_uid db.JSONNullString  `json:"w_upd_uid"`
    W_cr_uid db.JSONNullString  `json:"w_cr_uid"`
}



func SQLVweburl(tab string,flag db.SQLOper)[]interface{}{
  x :=   "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid"

  switch flag{
    case db.GenSelect:
    return []interface{}{
    x,
      tab,
      "id",
    }
    case db.GenInsert:
    return    []interface{}{ tab,
       "url,zusatz,created,w_cr_date,w_cr_uid"  ,
       "$1,$2,$3,current_timestamp,'webSrv'" ,
        x,
      }
    default:
      return    []interface{}{ tab,
        "url=$1,zusatz=$2,created=$3,w_upd_date=current_timestamp,w_upd_uid='webSrv'"  ,
        "id=$4",
      x,
        }

  }

}


func EmptyVweburl() interface{}{
    return new(Vweburl)
}


func ScannerVweburl()( []interface{}, interface{}){
	struT := new(Vweburl)

return  []interface{}{
				&struT.Id,
				&struT.Url,
				&struT.Zusatz,
				&struT.Created,
				&struT.W_cr_date,
				&struT.W_upd_date,
				&struT.W_upd_uid,
				&struT.W_cr_uid,
			}, struT

}


func ScannerTVweburl()( []interface{},*Vweburl){
	struT := new(Vweburl)

return  []interface{}{
				&struT.Id,
				&struT.Url,
				&struT.Zusatz,
				&struT.Created,
				&struT.W_cr_date,
				&struT.W_upd_date,
				&struT.W_upd_uid,
				&struT.W_cr_uid,
			}, struT

}


func ROWInsertVweburl(inter interface{})[]interface{}{
  rt := inter.( *Vweburl )
  return []interface{}{
	&rt.Url,
	&rt.Zusatz,
	&rt.Created,  }

}
