
// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by robots at
// 2017-04-12 22:41:08.111487671 +0200 CEST
//code for table vweburl

package gener



import (
	"restfest/db"
	"fmt"
	"time"
)

var dummyVweburl time.Time

type VweburlParams struct {
    Length int `schema:"length"`
    Offset int `schema:"offset"`
}


type Vweburl struct {
    Id *int32  `json:"id"`
    Url *string  `json:"url"`
    Zusatz *int64  `json:"zusatz"`
    Created *time.Time  `json:"created"`
    W_cr_date *time.Time  `json:"w_cr_date"`
    W_upd_date *time.Time  `json:"w_upd_date"`
    W_upd_uid *string  `json:"w_upd_uid"`
    W_cr_uid *string  `json:"w_cr_uid"`
}



func SQLVweburl(flag db.SQLOper)string{
  x :=   "id,url,zusatz,created,w_cr_date,w_upd_date,w_upd_uid,w_cr_uid"

  switch flag{
			
    case db.GenSelectID:
    return fmt.Sprintf(db.SQLPattern[db.GenSelectID],
    x,
	     "vweburl"	,
      "id" ,
    )

		case db.GenSelectAll:
		return fmt.Sprintf(db.SQLPattern[db.GenSelectAll],
		x,
   "vweburl"	,
  "id",
		)

		case db.GenInsert:
		return  fmt.Sprintf( db.SQLPattern[db.GenInsert],
			"vweburl"	,
			 "url,zusatz,created,w_cr_date,w_cr_uid"  ,
			 "$1,$2,$3,current_timestamp,'webSrv'" ,
				x)

				case db.GenDelete:
				return  fmt.Sprintf(db.SQLPattern[db.GenDelete]  ,
					"vweburl"	,
						"id",
						x)
				case db.GenUpdate:
				return  fmt.Sprintf(db.SQLPattern[db.GenUpdate]  ,
					"vweburl"	,
						"url=$1,zusatz=$2,created=$3,w_upd_date=current_timestamp,w_upd_uid='webSrv'"  ,
						"id=$4",
					x)

			
  }

	return ""

}


func EmptyVweburl() interface{}{
    return new(Vweburl)
}


func EmptyParamVweburl() interface{}{

 rt := new(VweburlParams)

	
		rt.Length=100
	

    return rt
}

func ScannerVweburl()( []interface{}, interface{}){
	struT := new(Vweburl)

return  []interface{}{
				&struT.Id,
				&struT.Url,
				&struT.Zusatz,
				&struT.Created,
				&struT.W_cr_date,
				&struT.W_upd_date,
				&struT.W_upd_uid,
				&struT.W_cr_uid,
			}, struT

}


func ScannerTVweburl()( []interface{},*Vweburl){
	struT := new(Vweburl)

return  []interface{}{
				&struT.Id,
				&struT.Url,
				&struT.Zusatz,
				&struT.Created,
				&struT.W_cr_date,
				&struT.W_upd_date,
				&struT.W_upd_uid,
				&struT.W_cr_uid,
			}, struT

}


func ROWInsertVweburl(inter interface{})[]interface{}{
					
  rt := inter.( *Vweburl )
	
  return []interface{}{
				
	&rt.Url,
	&rt.Zusatz,
	&rt.Created,

  }

}


func ROWQueryVweburl(inter interface{})[]interface{}{
  rt := inter.( *VweburlParams )

  return []interface{}{
		&rt.Length,
		&rt.Offset,
}

}
